INSERT INTO product_category (name, description) VALUES ('Wizard', 'Magical guy with wand or walking stick');
INSERT INTO product_category (name, description) VALUES ('Muggle', 'Non-magical guy without wand or walking stick');
INSERT INTO product_category (name, description) VALUES ('Hobbit', 'Hairy soled cute little alcoholic creature');
INSERT INTO product_category (name, description) VALUES ('Elf', 'Guy with pointy ears');
INSERT INTO product_category (name, description) VALUES ('Dwarf', 'Stuffy hairy caveman');
INSERT INTO product_category (name, description) VALUES ('Jedi', 'Cloaked man with a colorful dingdong');
INSERT INTO product_category (name, description) VALUES ('Sith', 'Evil cloaked man with a red dingdong');
INSERT INTO product_category (name, description) VALUES ('Human', 'Not much really');
INSERT INTO product_category (name, description) VALUES ('Dragon', 'Fire-breathing winged pet');
INSERT INTO product_category (name, description) VALUES ('Dark Lord', 'Attention ladies! This is the group of bad guyz');

INSERT INTO supplier (name, description) VALUES ('Harry Potter', 'Magic world of the boy who lived');
INSERT INTO supplier (name, description) VALUES ('Lord of the Rings', 'Tale of sneaky little hobbits');
INSERT INTO supplier (name, description) VALUES ('Game of Thrones', 'Medieval series with swords and titties');
INSERT INTO supplier (name, description) VALUES ('Star Wars', 'Armless and legless people fight in space');

INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Gandalf the Grey', 'Fantastic price. Changeable cloak (grey and white).', 49.9, 'USD', 2, 1);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Uncle Vernon', 'Fat guy with abusive attitude', 19.9, 'USD', 1, 2);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Samwise Gamgee', 'He cannot carry the ring but he can carry you', 59.9, 'USD', 2, 3);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Frodo Baggins', 'Tiny ringbearer with curly hair and disturbingly blue eyes', 49.9, 'USD', 2, 3);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Legolas', 'Perfect for seeing issues. Sees everything instead of you', 34.9, 'USD', 2, 4);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Aragorn', 'Heir of Isildur and a bad-ass elf-girl hunter. Greatest warrior of Middle-Earth', 54.9, 'USD', 2, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Boromir', 'Do not trust this man! Will probably try to take the ring!!4!', 14.9, 'USD', 2, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Ron Weasley', E'Unimportant ginger buddy. Suites well for French people \'cos he eats snails as fast as hell', 19.9, 'USD', 1, 1);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES (1, 'The choosen one with the scar on his head', 29.9, 'USD', 1, 1);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Hermione Granger', E'Crush of every 90\'s kid', 39.9, 'USD', 1, 1);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Albus Dumbledore', 'Manipulative old chap but his beard is cool. Probably cousin of Gandalf', 59.9, 'USD', 1, 1);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Norbert', E'Fascinating misunderstood creature of Hagrid\'s. May wear some Romanian cultural traces', 24.9, 'USD', 1, 9);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Hagrid', E'He\'s a bigger Gimli and a beast-lover semi-giant. It\'s a shame he is mentioned under this category but let\'s be honest he\'s greatest skill is creating a pigtail with an umbrella', 44.9, 'USD', 1, 2);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Gimli', E'He would die before he sees the ring in an elf\'s hand', 44.9, 'USD', 2, 5);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Drogon', 'Gigantic aggressive dragon aka The Winged Shadow', 69.9, 'USD', 3, 9);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Dobby', 'Well he may not be as cool as Middle-Earth elves this little boi is a useful tool in defeating dark lords. Has a fetish on socks', 49.9, 'USD', 1, 4);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Obi Wan Kenobi', 'Hello there', 24.9, 'USD', 4, 6);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Anakin Skywalker', 'Psychological wreck aka Darth Vader', 20.9, 'USD', 4, 7);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Master Windu', 'Black guy with long purple lightsaber', 24.9, 'USD', 4, 6);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Lord Voldemort', E'Noseless snaky-sneaky guy. Defeated by an infant so he\'s kind of a looser. Buy one and take one for free!', 9.9, 'USD', 1, 10);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Sauron', 'Former president of Middle-Earth. Was not re-elected due to some issues with stolen jewelery', 33.9, 'USD', 2, 10);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Darth Sidious', 'He has power. Un. Limited. Power.', 54.9, 'USD', 4, 10);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Darth Plagueis', E'He\'s one of the most ironic guys.. He could save others from death but not himself. What a prank', 34.9, 'USD', 4, 10);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Saruman', 'Leader of a giant orc-army. Likes to blow up mountains and to bungee-jumping from high towers', 43.9, 'USD', 2, 10);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('General Grievous', 'Bad lunged guy with replacable arms. Abandons ship way too early.', 24.9, 'USD', 4, 7);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Count Dooku', 'Old creepy-looking fellow. Twin brother of Saruman', 30.9, 'USD', 4, 7);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Jamie Lannister', 'One-handsome knight praised and hated by his world. Tends to stab kings and sisters.', 44.9, 'USD', 3, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Tyrion Lannister', 'Sharp-tongued sharp-minded alcoholic pervert hates by his sister. Always helps cripples and broken things.', 64.9, 'USD', 3, 5);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Ned Stark', 'Honourable fool of the North. Spoiler alert: he dies', 44.9, 'USD', 3, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Robb Stark', 'Latest king of the North with a pack of wolves behind his back. Spoiler alert: he dies', 24.9, 'USD', 3, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Daenerys Targaryen', 'Mother of some skinny winged creatures and a living speaking Schwarzkopf-ad', 44.9, 'USD', 3, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Varys', 'Ornithologist of Kingslanding who is always playing around with his little birds. Not very good at ball games.', 14.9, 'USD', 3, 8);
INSERT INTO product (name, description, price, currency, supplier_id, category_id) VALUES ('Littlefinger', 'Mafia boss of Kingslanding. Has an incurable crush on a woman which he tries to repress with drugs and prostitution', 22.9, 'USD', 3, 8);